language: android
jdk:
  - oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.1
  - android-24
 # Emulator for the tests
  - sys-img-armeabi-v7a-android-23

notifications:
  email: false

before_install:
  - pip install --user codecov
  # Install base Android SDK
  #- sudo apt-get update -qq
  #- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  #- wget http://dl.google.com/android/android-sdk_r24.0.1-linux.tgz
  #- tar xzf android-sdk_r24.0.1-linux.tgz
  #- export ANDROID_HOME=$PWD/android-sdk-linux
  #- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required Android components.
  #- echo y | android update sdk --filter platform-tools,android-24,extra-android-support,$ANDROID_SDKS --no-ui --force

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force --n test --t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
 - sudo chmod +x gradlew
 - ./gradlew check -PdisablePreDex --continue --stacktrace
 - android-wait-for-emulator
 - adb devices
 - adb shell input keyevent 82 &amp;
 - ./gradlew connectedCheck lint
 - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
 - ./gradlew connectedInstrumentTest


after_success:
  - ./gradlew jacocoFullReport
  - pip install --user codecov
  - codecov